-- Conformed repo entity for the curated layer.
select
    repo_id,
    repo_name,
    star_count,
    fork_count,
    event_count,
    first_seen_at,
    last_seen_at,
    description,
    primary_language,
    topics,
    license,
    open_issues_count,
    readme_length,
    repo_created_at,
    pushed_at,
    repo_size_kb,
    has_tests,
    has_ci,
    contributors_count,
    commit_count_30d,
    is_fork,
    is_archived,
    forks_count,
    subscribers_count,
    homepage,
    enriched_at,
    enrichment_status,
    enrichment_status = 'ok' as is_enriched
from {{ ref('stg_github_repos') }}
